/*globals define, _*/
/**
 * Generated by DecoratorGenerator
 */

define([
    'js/Decorators/DecoratorBase',
    './DiagramDesigner/TaskDecorator.DiagramDesignerWidget',
    './PartBrowser/TaskDecorator.PartBrowserWidget'
], function (DecoratorBase, TaskDecoratorDiagramDesignerWidget, TaskDecoratorPartBrowserWidget) {

    'use strict';

    var DECORATOR_ID = 'TaskDecorator';

    function TaskDecorator(params) {
        var opts = _.extend({loggerName: this.DECORATORID}, params);

        DecoratorBase.apply(this, [opts]);

        this.logger.debug('TaskDecorator ctor');
    }

    _.extend(TaskDecorator.prototype, DecoratorBase.prototype);
    TaskDecorator.prototype.DECORATORID = DECORATOR_ID;

    /*********************** OVERRIDE DecoratorBase MEMBERS **************************/

    TaskDecorator.prototype.initializeSupportedWidgetMap = function () {
        this.supportedWidgetMap = {
            DiagramDesigner: TaskDecoratorDiagramDesignerWidget,
            PartBrowser: TaskDecoratorPartBrowserWidget
        };
    };

    return TaskDecorator;
});
